In [97]:
import librosa
import numpy as np
import os
import pandas as pd
PATH = 'Notes Datasets/'
datas = []

In [98]:
def pitch(audio, label):
  y, sr = librosa.load(audio)
  signal, _ = librosa.effects.trim(y, top_db=2)
  fft = librosa.stft(signal, center = False)
  energi = abs(fft)**2
  data = pd.DataFrame(energi[:70])
  index = data.max().idxmax()
  formatted_data = map(lambda x: format(x, '.2f'), data[index])
  data =  list(formatted_data)
  data.append(label)
  return data

In [99]:
n = '04. Test'
n[4:]

'Test'

In [100]:
print(pitch('Notes Datasets/04. G/04-G-2.wav', 'E'))

['0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.02', '11.02', '65.24', '23.13', '0.03', '0.01', '0.00', '0.00', '0.03', '0.08', '38.25', '282.74', '128.68', '0.84', '0.03', '0.00', '0.00', '0.00', '0.00', '0.61', '7.47', '5.26', '0.15', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.04', '0.03', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.02', '0.03', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.01', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.01', '0.74', '3.98', '0.97', '0.01', '0.00', '0.00', '0.00', 'E']

In [101]:
for i in os.listdir(PATH):
  for j in os.listdir(f'{PATH}/{i}'):
    # print(f'{j}')
    datas.append(pitch((f'{PATH}/{i}/{j}'), i[4:]))

In [105]:
df = pd.DataFrame(datas)
df

,0,1,2,3,4,5,6,7,8,9,...,61,62,63,64,65,66,67,68,69,70
0,0.00,0.00,0.01,0.01,0.02,0.01,0.24,15.55,23.98,2.39,...,5.34,8.84,1.93,0.15,0.27,0.23,0.12,10.79,47.52,E
1,0.00,0.00,0.00,0.03,0.05,0.05,0.23,5.48,11.17,1.76,...,26.26,62.07,8.37,0.51,0.13,0.23,0.11,0.35,4.36,E
2,0.00,0.00,0.00,0.00,0.04,0.34,5.31,463.19,801.52,75.41,...,0.82,2.16,0.32,0.00,0.00,0.00,0.00,0.02,0.71,E
3,0.00,0.00,0.00,0.01,0.08,1.24,18.19,517.44,903.08,109.94,...,0.01,0.01,0.03,0.07,0.13,0.21,0.16,0.19,0.28,E
4,0.00,0.00,0.00,0.40,3.53,12.87,11.28,130.15,205.02,46.71,...,2.38,4.18,0.41,0.02,0.07,0.10,0.07,0.09,3.01,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,0.06,0.02,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,...,3455.90,2314.50,69.53,2.24,0.28,0.02,0.08,0.53,0.18,E3
2249,0.00,0.00,0.27,0.79,0.25,0.06,0.10,0.00,0.01,0.05,...,117.64,2.89,0.96,1.49,0.16,0.02,0.03,0.12,0.26,E3
2250,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,580.28,24.85,0.40,0.05,0.01,0.05,0.22,0.10,0.00,E3
2251,0.88,0.47,0.01,0.00,0.18,0.26,0.02,0.00,0.00,0.06,...,9224.96,197.08,5.37,1.06,0.23,0.09,0.00,0.00,0.00,E3
2252,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,...,1063.29,22.17,0.49,0.09,0.01,0.02,0.02,0.00,0.00,E3

In [106]:
df.to_csv('data.csv', index=False)

## Read Data

In [107]:
import pandas as pd
df = pd.read_csv('data.csv')

In [108]:
df

,0,1,2,3,4,5,6,7,8,9,...,61,62,63,64,65,66,67,68,69,70
0,0.00,0.00,0.01,0.01,0.02,0.01,0.24,15.55,23.98,2.39,...,5.34,8.84,1.93,0.15,0.27,0.23,0.12,10.79,47.52,E
1,0.00,0.00,0.00,0.03,0.05,0.05,0.23,5.48,11.17,1.76,...,26.26,62.07,8.37,0.51,0.13,0.23,0.11,0.35,4.36,E
2,0.00,0.00,0.00,0.00,0.04,0.34,5.31,463.19,801.52,75.41,...,0.82,2.16,0.32,0.00,0.00,0.00,0.00,0.02,0.71,E
3,0.00,0.00,0.00,0.01,0.08,1.24,18.19,517.44,903.08,109.94,...,0.01,0.01,0.03,0.07,0.13,0.21,0.16,0.19,0.28,E
4,0.00,0.00,0.00,0.40,3.53,12.87,11.28,130.15,205.02,46.71,...,2.38,4.18,0.41,0.02,0.07,0.10,0.07,0.09,3.01,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,0.06,0.02,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,...,3455.90,2314.50,69.53,2.24,0.28,0.02,0.08,0.53,0.18,E3
2249,0.00,0.00,0.27,0.79,0.25,0.06,0.10,0.00,0.01,0.05,...,117.64,2.89,0.96,1.49,0.16,0.02,0.03,0.12,0.26,E3
2250,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,580.28,24.85,0.40,0.05,0.01,0.05,0.22,0.10,0.00,E3
2251,0.88,0.47,0.01,0.00,0.18,0.26,0.02,0.00,0.00,0.06,...,9224.96,197.08,5.37,1.06,0.23,0.09,0.00,0.00,0.00,E3
2252,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,...,1063.29,22.17,0.49,0.09,0.01,0.02,0.02,0.00,0.00,E3